#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# User configuration

export GOPATH=~/go

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/texbin:/Users/aaron/.rvm/gems/ruby-2.0.0-p451/bin:/Users/aaron/.rvm/gems/ruby-2.0.0-p451@global/bin:/Users/aaron/.rvm/rubies/ruby-2.0.0-p451/bin:/Users/aaron/.rvm/bin:/Users/aaron/Library/Haskell/bin:/usr/local/sbin:/usr/local/heroku/bin:/Applications/Postgres.app/Contents/MacOS/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/opt/local/bin:/opt/local/sbin:/Users/aaron/Documents/keep_forever:/Users/aaron/.rvm/bin:/Applications/Racket v6.2.1/bin:$GOPATH/bin"

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/aaron/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

# use MacVim instead of old vim
alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"

# git commands simplified
alias gsu='git status'
alias gdi='git diff'
alias gdic='git diff --cached'
alias gch='git checkout'
alias gco='git commit -m'
alias gcoa='git commit --amend'
alias gre='git rebase'
alias gbr='git branch'
alias gad='git add'
alias gpul='git pull origin'
alias gpus='git push origin'
alias gfe='git fetch'
alias gst='git stash'
alias gsp='git stash pop'
alias tia='tig --all'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#
# Prompt
#

# Use vim cli mode.
bindkey '^P' up-history
bindkey '^N' down-history
bindkey "^U" backward-kill-line

# ctrl-r starts searching history backward.
bindkey '^r' history-incremental-search-backward
