#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# User configuration

export GOPATH=~/go

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/texbin:~/.rvm/gems/ruby-2.0.0-p451/bin:~/.rvm/gems/ruby-2.0.0-p451@global/bin:~/.rvm/rubies/ruby-2.0.0-p451/bin:~/.rvm/bin:~/Library/Haskell/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/MacOS/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/opt/local/bin:/opt/local/sbin:~/Documents/keep_forever:~/.rvm/bin:$GOPATH/bin:`yarn global bin`"

# use MacVim instead of old vim
alias vim="nvim"
alias oldvim="/Applications/MacVim.app/Contents/MacOS/Vim"

# git commands simplified
alias gsu='git status'
alias gdi='git diff'
alias gdic='git diff --cached'
alias gch='git checkout'
alias gco='git commit -m'
alias gcoa='git commit --amend'
alias gre='git rebase'
alias gbr='git branch'
alias gad='git add'
alias gpul='git pull origin'
alias gpus='git push origin'
alias gfe='git fetch'
alias gst='git stash'
alias gsp='git stash pop'
alias tia='tig --all'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#
# Prompt
#

# Use vim cli mode.
bindkey '^P' up-history
bindkey '^N' down-history
bindkey "^U" backward-kill-line

# Don't share history between terminal windows.
setopt no_share_history
unsetopt share_history

# ctrl-r starts searching history backward.
bindkey '^r' history-incremental-search-backward

export WORKON_HOME=~/Envs
export VIRTUALENVWRAPPER_PYTHON=`which python3`
source /usr/local/bin/virtualenvwrapper_lazy.sh

export NVM_DIR="~/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

export FZF_DEFAULT_COMMAND='ag -g ""'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GPG_TTY=`tty`
