#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# User configuration

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/texbin:$HOME/Library/Haskell/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/MacOS/bin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/opt/local/bin:/opt/local/sbin:$HOME/Documents/keep_forever:$HOME/go/bin:/usr/local/lib/ruby/gems/2.5.0:/Applications/CMake.app/Contents/bin"

# use MacVim instead of old vim
alias vim="nvim"

# git commands simplified
alias gsu='git status'
alias gdi='git diff'
alias gdic='git diff --cached'
alias gch='git checkout'
alias gco='git commit -m'
alias gcoa='git commit --amend'
alias gre='git rebase'
alias gbr='git branch'
alias gad='git add'
alias gpul='git pull origin'
alias gpus='git push origin'
alias gfe='git fetch'
alias gst='git stash'
alias gsp='git stash pop'
alias tia='tig --all'

# Use exa instead of ls: https://github.com/ogham/exa
alias ls='exa'

# Use bat instead of cat: https://github.com/sharkdp/bat
alias cat='bat'

#
# Prompt
#

# Use vim cli mode.
bindkey '^P' up-history
bindkey '^N' down-history
bindkey "^U" backward-kill-line

# Don't share history between terminal windows.
setopt no_share_history
unsetopt share_history

# ctrl-r starts searching history backward.
bindkey '^r' history-incremental-search-backward

export WORKON_HOME=~/Envs

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export PATH="/Users/dblarons/Library/Python/3.9/bin:$PATH"

# opam configuration
[[ ! -r /Users/dblarons/.opam/opam-init/init.zsh ]] || source /Users/dblarons/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
